# Generated by Django 4.2.7 on 2025-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
