# Generated by Django 4.2.7 on 2025-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_herosection_options_herosection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('primary_color', models.CharField(default='#0477BF', max_length=7)),
                ('secondary_color', models.CharField(default='#012340', max_length=7)),
                ('accent_color', models.CharField(default='#FCB316', max_length=7)),
                ('light_color', models.CharField(default='#048ABF', max_length=7)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
            },
        ),
    ]
