# Generated by Django 4.2.7 on 2025-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_colorpalette'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Your Company', max_length=100)),
                ('title', models.CharField(default='We Execute Ideas\nFrom Start to Finish', max_length=200)),
                ('button_text', models.CharField(default='Know More', max_length=50)),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_description', models.TextField(default='Our mission is to push boundaries, engage audiences, and drive innovation through cutting-edge technology solutions.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_description', models.TextField(default='To become the leading software house that transforms businesses through innovative digital solutions and exceptional user experiences.')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('floating_text', models.TextField(default='Repellendus autem ruibusdam at aut officiis debitis aut re necessitatibus saepe eveniet ut et repudianda sint et molestiae non recusandae.')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
