# Generated by Django 4.2.7 on 2025-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='OUR OFFERING', max_length=100)),
                ('title', models.CharField(default='Enhance And Pioneer Using', max_length=200)),
                ('title_highlight', models.CharField(default='Technology Trends', max_length=100)),
                ('button_text', models.CharField(default='Explore More', max_length=50)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='mission_description',
            field=models.TextField(default='Our mission is to push boundaries, engage audiences, drive innovation through cutting-edge technology solutions.'),
        ),
    ]
