# Generated by Django 4.2.7 on 2025-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_servicessection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Custom SVG icon code', null=True),
        ),
    ]
