# Generated by Django 4.2.7 on 2025-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_service_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
