# Generated by Django 4.2.7 on 2025-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_whychooseusfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='OUR STRENGTHS', max_length=100)),
                ('title', models.CharField(default='WHY CHOOSE INNO8', max_length=200)),
                ('breadcrumb_items', models.CharField(default='Experience,Innovation,Results', help_text='Comma separated items', max_length=200)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
    ]
