# Generated by Django 4.2.7 on 2025-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_clientlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='How We Work', max_length=100)),
                ('title', models.CharField(default='Our Working Process', max_length=200)),
                ('description', models.TextField(default='We follow a proven methodology to deliver exceptional results for every project')),
            ],
            options={
                'verbose_name': 'Working Process Section',
                'verbose_name_plural': 'Working Process Section',
            },
        ),
        migrations.CreateModel(
            name='WorkingProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(help_text='SVG icon code')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Working Process Step',
                'verbose_name_plural': 'Working Process Steps',
                'ordering': ['order'],
            },
        ),
    ]
