# Generated by Django 4.2.7 on 2025-12-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_workingprocesssection_workingprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Client Testimonials', max_length=100)),
                ('title', models.CharField(default='What Our Clients Say', max_length=200)),
                ('description', models.TextField(default="Don't just take our word for it. Here's what our satisfied clients have to say about our services.")),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
