# Generated by Django 4.2.7 on 2025-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_testimonialssection_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('icon_svg', models.TextField(help_text='SVG icon code')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Get In Touch', max_length=100)),
                ('title', models.CharField(default='Contact Us', max_length=200)),
                ('description', models.TextField(default="Ready to transform your ideas into reality? Let's build something amazing together.")),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
    ]
