# Generated by Django 4.2.7 on 2025-12-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_contactinfo_contactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('author', models.CharField(default='Inno8 Team', max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='BlogsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Latest News', max_length=100)),
                ('title', models.CharField(default='Our Blog', max_length=200)),
                ('description', models.TextField(default='Stay updated with our latest insights, tips, and industry news.')),
            ],
            options={
                'verbose_name': 'Blogs Section',
                'verbose_name_plural': 'Blogs Section',
            },
        ),
    ]
