# Generated by Django 4.2.7 on 2025-12-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_blogpost_blogssection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['date_published'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
