# Generated by Django 4.2.7 on 2025-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_teammember_teamsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='overview_description1',
            field=models.TextField(default='Founded with a vision to bridge the gap between innovative technology and business success, Inno8 has been at the forefront of digital transformation.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='overview_description2',
            field=models.TextField(default='Our team combines technical expertise with creative thinking to deliver solutions that are functional, user-friendly and scalable.'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='overview_title',
            field=models.CharField(default='Company Overview', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='projects_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='years_experience',
            field=models.IntegerField(default=5),
        ),
    ]
