# Generated by Django 4.2.7 on 2025-12-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='learn_more_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
