# Generated by Django 4.2.7 on 2026-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_sitesettings_maintenance_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Testimonial Submission',
                'verbose_name_plural': 'Testimonial Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
