# Generated by Django 4.2.7 on 2026-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
