# Generated by Django 4.2.7 on 2026-02-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pagevisit_browser_pagevisit_city_pagevisit_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='traffic_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
